GROQ_API_KEY="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"
OPENAI_API_KEY="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"
